"""add column phone_number to users

Revision ID: 6f8b3dac46a2
Revises: 2891a9b03957
Create Date: 2022-11-05 21:35:32.940500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8b3dac46a2'
down_revision = '2891a9b03957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("phone_number", 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
